[package]
name = "fractal"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.11"
wgpu = "25.0.2"
pollster = "0.3"
cfg-if = "1.0"
bytemuck = { version = "1.23.0", features = ["derive"] }
